apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: moodle-pdb
  namespace: ${NAMESPACE}
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app: moodle
---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: pgbouncer-pdb
  namespace: ${NAMESPACE}
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app: pgbouncer
---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: pgbouncer-read-pdb
  namespace: ${NAMESPACE}
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app: pgbouncer-read
